### ISSUE TITLE
Separator Error

### ISSUE THREAD

**Issue by archenop** [Montvydas/translatesubs#2]
I can't access the website you mention, so this project is my last hope before I translate manually line by line

D:\IDM\RAR\lucky star budoukan>translatesubs [SOSG][Lucky_Star_in_Budoukan][01][DVDrip][X264_AC3][848x480](DCE62386).sc.ass out.ass --to_lang en --encoding "utf-16"
Translating to "english".
Trying separator " $$$ "...
original length=2254, translated length=1884
Trying separator " ### "...
original length=2254, translated length=1478
Trying separator " ∞ "...
original length=2254, translated length=1320
Trying separator "@@@"...
original length=2254, translated length=2715
Trying separator " ™ "...
original length=2254, translated length=94
Trying separator " @@@ "...
original length=2254, translated length=2645
Trying separator "$$$"...
original length=2254, translated length=1887
Trying separator "€€€"...
original length=2254, translated length=473
Trying separator "££"...
original length=2254, translated length=1150
Trying separator " ## "...
original length=2254, translated length=1519
Trying separator "@@"...
original length=2254, translated length=2052
Trying separator "$$"...
original length=2254, translated length=1805
It seems like all tries to translate got corrupted. Try to manually set the separator using --separator argument to be DIFFERENT from: " $$$ ", " ### ", " ∞ ", "@@@", " ™ ", " @@@ ", "$$$", "€€€", "££", " ## ", "@@", "$$". Check --help menu for more information.

D:\IDM\RAR\lucky star budoukan>translatesubs [SOSG][Lucky_Star_in_Budoukan][01][DVDrip][X264_AC3][848x480](DCE62386).sc.ass out.ass --to_lang en --encoding "utf-16" --separator "&&&"
Translating to "english".
Trying separator "&&&"...
original length=2254, translated length=2813
It seems like all tries to translate got corrupted. Try to manually set the separator using --separator argument to be DIFFERENT from: " $$$ ", " ### ", " ∞ ", "@@@", " ™ ", " @@@ ", "$$$", "€€€", "££", " ## ", "@@", "$$". Check --help menu for more information.

**Comment by Montvydas** [comment]
The way it is, not every subs file will get translated, especially for foreign characters. The tool is done in a way, which would allow anyone to use the tool WITHOUT entering a google translate API key, however then if you make too many requests, your account will get banned.. Thus subtitles are being grouped into larger chunks, separated by special separator and then later the result is being split by that same separator, which ensures that you do not get banned. This works for the majority of cases, however as you can see for your translation it does not and there is no way to solve it since the problem is you send one thing to google translate, however are returned something very different... In this case I would recommend searching alternative translator, which can handle translating subs one by one instead.
